version: "3.7"

services:
  local_postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment: 
      POSTGRES_USERNAME: admin
      POSTGRES_PASSWORD: admin
      PGDATA: db/postgres
    volumes:
      - postgres-db:/var/lib/postgresql/data
    ports: 
      - "5432:5432"

volumes:
  postgres-db:
    driver: local
